# Generated by Django 4.1.13 on 2024-10-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_userchathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchathistory',
            options={},
        ),
        migrations.RenameField(
            model_name='userchathistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterModelTable(
            name='userchathistory',
            table='userchathistory',
        ),
    ]
